//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample03
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cidade
    {
        public Cidade()
        {
            this.PessoaTBs = new HashSet<PessoaTB>();
        }
    
        public int CidadeId { get; set; }
        public string Descricao { get; set; }
        public string Sigla { get; set; }
    
        public virtual ICollection<PessoaTB> PessoaTBs { get; set; }
    }
}
